### ISSUE TITLE
     TypeError: expect(...).to.have.been.called is not a function

### ISSUE THREAD

**Issue by zenosu** [domenic/sinon-chai#82]
We found a little issue, and recreated it in a single test file:

```JavaScript
const chai = require('chai')
const sinonChai = require('sinon-chai');
const spy = require('sinon').spy;
const expect = chai.expect;
chai.use(sinonChai);

it('does not spy', function () {
  const mySpy = spy()
  expect(mySpy).to.have.been.called();
});

it('should, however, spy', function () {
  const mySpy = spy()
  mySpy()
  expect(mySpy).to.have.been.called();
});
```

Although `sinon-chai` gives great failure messages:
```
1)  does not spy:
     AssertionError: expected spy to have been called at least once, but it was never called
      at Context.<anonymous> (test/test.js:9:29)
```

When it seems it should pass, it gives a rather disappointing message:
```
 2)  should, however:
     TypeError: expect(...).to.have.been.called is not a function
      at Context.<anonymous> (test/test.js:15:30)
```

package.json for reference:
```json
{
  "dependencies": {
    "chai": "^3.5.0",
    "mocha": "^3.1.1",
    "sinon": "^1.17.6",
    "sinon-chai": "^2.8.0"
  }
}
```

**Comment by domenic** [comment]
As explained in the readme, called is not a function, it's a property. Omit the parentheses.
