### ISSUE TITLE
[feature-request] add chai colored diff to "calledWith" expectations

### ISSUE THREAD

**Issue by eauc** [domenic/sinon-chai#93]
Hi,

actually when this kind of expectation fails:
```
expect(getSoundUrlFromName)
	.to.have.been.calledWith(this.node.soundname, {
		accountId: this.accountId,
		scriptId: this.scriptId,
		onSuccess: sinon.match.object,
	});
```

I get an error message looking like this:
```
expected getSoundUrlFromName to have been called with arguments otherSoundname, { accountId: "accountId", onSuccess: typeOf("object"), scriptId: "otherScriptId" }
    getSoundUrlFromName(otherSoundname, {
  accountId: "accountId",
  onSuccess: function getVerbs() {},
  scriptId: "otherScriptId"
}) => webModel.getSoundUrlFromName.returnValue at...
```

Which is fine but sometimes it's hard to know exactly what doesn't match in the arguments... especially when we have multiples calls to the spy.

I'd like to add the chai colored diff between the expected arguments list and all the arguments list for all the calls.

I've looked into the code and made a (very very dirty) hack to make this work:
lib/sinon-chai.js:86
```
    function createSinonMethodHandler(sinonName, action, nonNegatedSuffix) {
        return function () {
            assertCanWorkWith(this);

            var alwaysSinonMethod = "always" + sinonName[0].toUpperCase() + sinonName.substring(1);
            var shouldBeAlways = utils.flag(this, "always") && typeof this._obj[alwaysSinonMethod] === "function";
            var sinonMethod = shouldBeAlways ? alwaysSinonMethod : sinonName;

          var messages = getMessages(this._obj, action, nonNegatedSuffix, shouldBeAlways, slice.call(arguments));
+	 var args = [];
+	for (var i = 0, l = this._obj.callCount; i < l; ++i) {
+          args.push(this._obj.getCall(i).args);
+	}
          this.assert(
		this._obj[sinonMethod].apply(this._obj, arguments),
		messages.affirmative,
		messages.negative,
+		[slice.call(arguments)],
+		args,
+		true
	);
    };
}
```

Which gives me an assertion message like:
```
expected getSoundUrlFromName to have been called with arguments otherSoundname, { accountId: "accountId", onSuccess: typeOf("object"), scriptId: "otherScriptId" }
    getSoundUrlFromName(null, { onSuccess: function onSuccess() {}, scriptId: "fim" }) => webModel.getSoundUrlFromName.returnValue at Context.<anonymous> (/home/auclair/smartcc/DojoIVR/test/models/nodes/announcementSpec.js:61:20)
    getSoundUrlFromName(otherSoundname, {
  accountId: "accountId",
  onSuccess: function getVerbs() {},
  scriptId: "otherScriptId"
}) => webModel.getSoundUrlFromName.returnValue at Object.play (/home/auclair/smartcc/DojoIVR/models/nodes/announcement.js:29:19)

    getSoundUrlFromName(otherSound, { accountId: "bof", onSuccess: function onSuccess() {} }) => webModel.getSoundUrlFromName.returnValue at ...
      + expected - actual

       [
         [
      -    [null]
      -    {
      -      "onSuccess": [Function]
      -      "scriptId": "fim"
      -    }
      -  ]
      -  [
           "otherSoundname"
           {
             "accountId": "accountId"
      -      "onSuccess": [Function]
      +      "onSuccess": {
      +        "message": "typeOf(\"object\")"
      +        "test": [Function]
      +      }
             "scriptId": "otherScriptId"
           }
         ]
      -  [
      -    "otherSound"
      -    {
      -      "accountId": "bof"
      -      "onSuccess": [Function]
      -    }
      -  ]
       ]
```

We can see that chai's diff algorithm does a good job of diffing the different arguments lists and finding the one that looks the most like what we expected, and greatly improve feedback on the error's source.

What do you think ?
(of course we would need to find a clean way to insert this into your lib)

**Comment by domenic** [comment]
We get the error messages directly from Sinon. You need to open the feature request there, not here.

**Comment by jimboslicethat** [comment]
@domenic It looks like Sinon added support for this back [here](https://github.com/sinonjs/sinon/pull/1203). It seems to be stable on its own without a third party assertion library. I may be grasping at straws, so help me out where I'm lacking knowledge, but does this mean there is an issue with `chai` creating diffs against the sinon error? I'm mostly just trying to figure out where I should submit a feature request. Thanks in advance!

**Comment by domenic** [comment]
It looks like we need to switch from %C to %D. I will reopen. A pull request would be welcome.

**Comment by domenic** [comment]
Oops, https://github.com/domenic/sinon-chai/commit/48d2408e2ada3778e0d07d04000adec7ec8dc7ce meant to close this, but it closed itself instead.
